"""
cli.py

CLI mode source code.
"""

import os
from ConfigParser import RawConfigParser
import requests
import logging
import json

import common
import http
import app_log


LOG = logging.getLogger("cli")


class RequestError(Exception):
    """Raised when there's an 'error' in the Server response."""
    pass


class Cli(object):
    """Runs the cli mode for this application.
    The cli mode executes JSON-RPC requests to the server
    and returns the 'result' to the user.
    If 'error' is not empty in the response,
    it raises a RequestError exception.
    """

    def __init__(self, options):
        self.options = options
        self.request_id = 0
        self.server_uri = ""
        self.server_config = {}
        app_log.setup_cli_logging(options.debug)
        self.load_from_server_config()

    def load_from_server_config(self):
        """Loads settings from config file generated by server.
        The config file path is read from an env variable.
        """
        config_dir_path = os.environ[common.CONFIG_DIR_ENV_VAR]
        config_file_name = os.path.join(
            config_dir_path,
            common.AUTOCONNECT_CONFIG_FILE_NAME)
        cfg = RawConfigParser()
        cfg.read(config_file_name)
        self.server_config = common.raw_config_as_dict(cfg)[
            common.AUTOCONNECT_CONFIG_SECTION]
        self.server_uri = self.server_config['uri']

    def run_method(self, method, args_dict):
        """Performs an JSON-RPC request to the server.
        Arguments:
        method : string, method name
        args_dict : dict, positional params
        """
        headers = {"content-type": "application/json"}
        payload = {
            "method": method,
            "params": args_dict,
            "id": self.request_id,
            "jsonrpc": "2.0",
        }
        LOG.debug("request: %s", payload)
        response = requests.post(
            self.server_uri,
            data=json.dumps(payload),
            headers=headers)
        response_data = json.loads(response.text, encoding='utf-8')
        LOG.debug("response: %s", response_data)
        assert self.request_id == response_data["id"]
        self.request_id += 1
        if "error" in response_data:
            raise RequestError(response_data["error"])
        return response_data["result"]

    def run(self):
        """Cli command execution.
        Returns the 'result' section from the JSON-RPC Server response.
        If there's an 'error' in the Server response,
        a RequestError is raised.
        """
        response = None
        if self.options.api:
            api_name = self.options.api.replace("-", "_")
            args_list = http.HttpApi.get_api_args(api_name)
            args_dict = {key: getattr(self.options, key)
                         for key in args_list}
            response = self.run_method(self.options.api, args_dict)
        return response
